- name: Add sickchill group
  group:
    name: "{{ sickchill_group }}"
    state: present
  become: yes

- name: Add sickchill user
  user:
    name: "{{ sickchill_user }}"
    state: present
    group: "{{ sickchill_group }}"
    home: "{{ sickchill_home }}"
    shell: /bin/bash
  become: yes

- name: Add sickchill user to the osmc group
  user:
    name: "{{ sickchill_user }}"
    groups: osmc
    append: yes
  become: yes
