- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  become: yes
  with_items:
    - git
    - python2.7
    - unrar
    - git-core
    - openssl
    - libssl-dev
