---
- import_tasks: install_dependencies.yml
- import_tasks: configure_user.yml
- import_tasks: clone_repo.yml
- import_tasks: setup_sickchill.yml
- import_tasks: restore_backup.yml
  when: sickchill_restore_backup