- name: Set web_username
  ini_file:
    path: "{{ sickrage_directory }}/config.ini"
    section: General
    option: web_username
    value: "{{ sickrage_web_user }}"
  become: yes

- name: Set web_password
  ini_file:
    path: "{{ sickrage_directory }}/config.ini"
    section: General
    option: web_password
    value: "{{ sickrage_web_pass }}"
  become: yes

- name: Ensure config.ini has the right permissions
  file:
    path: "{{ sickrage_directory }}/config.ini"
    owner: "{{ sickrage_user }}"
    group: "{{ sickrage_group }}"
  become: yes

- name: Copy sickrage systemd unit file
  command: cp {{ sickrage_directory }}/runscripts/init.systemd /etc/systemd/system/sickrage.service
  become: yes

- name: Ensure sickrage.service has the right permissions
  file:
    path: /etc/systemd/system/sickrage.service
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Enable sickrage service
  command: systemctl enable sickrage.service
  become: yes

- name: Start sickrage
  command: systemctl start sickrage.service
  become: yes
