- name: Download libtorrent
  get_url:
    url: "http://rtorrent.net/downloads/libtorrent-{{ libtorrent_version }}.tar.gz"
    dest: /home/osmc/src/

- name: Extract libtorrent
  command: "tar xzf libtorrent-{{ libtorrent_version }}.tar.gz"
  args:
    chdir: /home/osmc/src/

- name: Autogen libtorrent
  shell: ./autogen.sh
  args:
    chdir: "/home/osmc/src/libtorrent-{{ libtorrent_version }}/"

- name: Configure libtorrent
  shell: ./configure
  args:
    chdir: "/home/osmc/src/libtorrent-{{ libtorrent_version }}/"

- name: Build libtorrent
  shell: make
  args:
    chdir: "/home/osmc/src/libtorrent-{{ libtorrent_version }}/"

- name: Install libtorrent
  shell: make install
  args:
    chdir: "/home/osmc/src/libtorrent-{{ libtorrent_version }}/"
  become: yes
