- name: Download rtorrent
  get_url:
    url: http://rtorrent.net/downloads/rtorrent-0.9.7.tar.gz
    dest: /home/osmc/src/

- name: Extract rtorrent
  command: tar xzf rtorrent-0.9.7.tar.gz
  args:
    chdir: /home/osmc/src/

- name: Autogen rtorrent
  shell: ./autogen.sh
  args:
    chdir: /home/osmc/src/rtorrent-0.9.7/

- name: Configure rtorrent
  shell: ./configure --with-xmlrpc-c=/usr/local/bin/xmlrpc-c-config
  args:
    chdir: /home/osmc/src/rtorrent-0.9.7/

- name: Build rtorrent
  shell: make
  args:
    chdir: /home/osmc/src/rtorrent-0.9.7/

- name: Install rtorrent
  shell: make install
  args:
    chdir: /home/osmc/src/rtorrent-0.9.7/
  become: yes

- name: Run ldconfig
  command: ldconfig
  become: yes
