- name: Download rtorrent
  get_url:
    url: "http://rtorrent.net/downloads/rtorrent-{{ rtorrent_version }}.tar.gz"
    dest: /home/osmc/src/

- name: Extract rtorrent
  command: "tar xzf rtorrent-{{ rtorrent_version }}.tar.gz"
  args:
    chdir: /home/osmc/src/

- name: Autogen rtorrent
  shell: ./autogen.sh
  args:
    chdir: "/home/osmc/src/rtorrent-{{ rtorrent_version }}/"

- name: Configure rtorrent
  shell: ./configure --with-xmlrpc-c=/usr/local/bin/xmlrpc-c-config
  args:
    chdir: "/home/osmc/src/rtorrent-{{ rtorrent_version }}/"

- name: Build rtorrent
  shell: make
  args:
    chdir: "/home/osmc/src/rtorrent-{{ rtorrent_version }}/"

- name: Install rtorrent
  shell: make install
  args:
    chdir: "/home/osmc/src/rtorrent-{{ rtorrent_version }}/"
  become: yes

- name: Run ldconfig
  command: ldconfig
  become: yes
