- name: Stop kodi
  service:
    name: mediacenter
    state: stopped
  become: yes

- name: Install dependencies
  apt:
    name: ['curl', 'mediainfo', 'mono-devel', 'libmono-cil-dev', 'sqlite3']
    state: latest
    update_cache: yes
  become: yes

- name: Start kodi
  service:
    name: mediacenter
    state: started
  become: yes
