- name: Stop kodi
  service:
    name: mediacenter
    state: stopped
  become: yes

- name: Install dependencies for mono repo
  apt:
    name: ['apt-transport-https', 'dirmngr', 'gnupg', 'ca-certificates']
    state: latest
    update_cache: yes
  become: yes

- name: Add mono-project apt-key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  become: yes

- name: Add mono-project repo
  apt_repository: >
    repo='deb https://download.mono-project.com/repo/debian stable-stretch main'
    state=present
    update_cache=yes
  become: yes

- name: Install dependencies
  apt:
    name: ['curl', 'mediainfo', 'mono-devel', 'libmono-cil-dev', 'sqlite3', 'mono-complete']
    state: latest
    update_cache: yes
  become: yes

- name: Start kodi
  service:
    name: mediacenter
    state: started
  become: yes
