- name: Stop kodi
  service:
    name: mediacenter
    state: stopped
  become: yes

- name: Install lxml to manage guisettings
 apt:
   name: python-lxml
   state: latest
   update_cache: yes
 become: yes

- name: Change the default web interface port
  xml:
    path: /home/osmc/.kodi/userdata/guisettings.xml
    xpath: setting[@id="services.webserverport"]
    value: '"{{kodi_web_interface_port}}"'

- name: Install nginx
  apt:
    name: nginx
    state: latest
  become: yes

- name: Install php
  apt:
    name: php-fpm
    state: latest
  become: yes

- name: Start kodi
  service:
    name: mediacenter
    state: started
  become: yes
